
function fish_prompt
    printf "> "
end

# Enable vi mode in fish shell
fish_vi_key_bindings

# Configure cursors for different vi modes
set fish_cursor_default block
set fish_cursor_insert line
set fish_cursor_replace_one underscore
set fish_cursor_visual block

function fish_mode_prompt
end

set EDITOR zed

# Disable greeting
set fish_greeting

# Suggested by homebrew
set PATH /usr/local/opt/ruby/bin /usr/local/sbin /usr/local/bin /opt/homebrew/bin /Users/tomb/.local/bin /Users/tomb/bin $PATH

# Square
set DEVELOPMENT_TEAM_ID B55P8QP425
rvm default

function be --wraps bundle
  bundle check &> /dev/null || bundle install
  bundle exec $argv
end

## Goose
# Make message text color readable in light terminal theme
set -x GOOSE_CLI_THEME light
# https://docs.google.com/document/d/19jIgWlLMxpYQr2V5gBYiVc1HH7fgzwJWT45CtLLhDFM/edit?tab=t.wq1h4mugqght#heading=h.rek6kjf7ar0w
set -x GOOGLE_DRIVE_OAUTH_PATH ~/.config/goose/mcp-gdrive/gcp-oauth.keys.json

# Commented out in a weird way to work around it being automatically re-added
# https://square.slack.com/archives/C01PCG3663Y/p1728515926256199?thread_ts=1728508299.633879&amp;cid=C01PCG3663Y
: '
### The lines in this section are added automatically by salt. Do not modify. ###
export PATH=$PATH:~/bin

# Generated by Hermit; START; DO NOT EDIT.
HERMIT_ROOT_BIN="${HERMIT_ROOT_BIN:-"$HOME/bin/hermit"}"
eval "$(test -x $HERMIT_ROOT_BIN && $HERMIT_ROOT_BIN shell-hooks --print --zsh)"
# Generated by Hermit; END; DO NOT EDIT.
######
'
mise activate fish | source
